name       : kleopatra
version    : 18.08.2
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kleopatra-18.08.2.tar.xz : 758c5ffa491749ca8ebf774c92a2ed1653680932d996b0b440c31a5f0124eefa
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde
summary    : Kleopatra is a GUI for GnuPG
description: |
    Kleopatra is a GUI for GnuPG so it needs a working GnuPG setup.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcodecs-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - kmime-devel
    - libassuan-devel
    - libboost-devel
    - libkleo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
