name       : kleopatra
version    : 21.08.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kleopatra-21.08.0.tar.xz : 7979cac5dc4a631c72eb5755ad7c762ebd32ad5fcb01e0d60d2b4577d9e80351
homepage   : https://kde.org/applications/utilities/org.kde.kleopatra
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : Kleopatra is a GUI for GnuPG
description: |
    Kleopatra is a GUI for GnuPG so it needs a working GnuPG setup.
builddeps  :
    - pkgconfig(libassuan)
    - gpgme-qt-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - kmime-devel
    - libboost-devel
    - libkleo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
