name       : kleopatra
version    : 18.12.1
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/kleopatra-18.12.1.tar.xz : b2961ace06eb9b93902f2b160520f533f7ad5108374ee67bcae49c465f744fda
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : Kleopatra is a GUI for GnuPG
description: |
    Kleopatra is a GUI for GnuPG so it needs a working GnuPG setup.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcodecs-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - kmime-devel
    - libassuan-devel
    - libboost-devel
    - libkleo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
