name       : kleopatra
version    : 17.08.3
release    : 1
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kleopatra-17.08.3.tar.xz : a8bb8bc8d6b6352f2d312f79ee2846217ffa699bff419673ebf70cdc1dbcf46d
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde
summary    : Kleopatra is a GUI for GnuPG
description: |
    Kleopatra is a GUI for GnuPG so it needs a working GnuPG setup.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcodecs-devel
    - kconfig-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - kmime-devel
    - libassuan-devel
    - libboost-devel
    - libkleo-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
