name       : kleopatra
version    : 19.08.2
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kleopatra-19.08.2.tar.xz : 7d0667b71796f8cbf9081c74c80def1e6618366400d4fbe56e690bb7049e4085
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : Kleopatra is a GUI for GnuPG
description: |
    Kleopatra is a GUI for GnuPG so it needs a working GnuPG setup.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcmutils-devel
    - kcoreaddons-devel
    - kcodecs-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - kmime-devel
    - libassuan-devel
    - libboost-devel
    - libkleo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
