name       : kleopatra
version    : 20.08.3
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/kleopatra-20.08.3.tar.xz : d15f2615a63e577d08fafddd1d705cffdd4324de137c543867850d0ecf4b07e5
homepage   : https://kde.org/applications/utilities/org.kde.kleopatra
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : Kleopatra is a GUI for GnuPG
description: |
    Kleopatra is a GUI for GnuPG so it needs a working GnuPG setup.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kcmutils-devel
    - kcoreaddons-devel
    - kcodecs-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - kmime-devel
    - libassuan-devel
    - libboost-devel
    - libkleo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
