name       : kleopatra
version    : 21.08.2
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/kleopatra-21.08.2.tar.xz : c9de8fe61cbdeb61f11be221c526c445fbfeb7016632bd34fa1827ca7b07a4fa
homepage   : https://kde.org/applications/utilities/org.kde.kleopatra
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : Kleopatra is a GUI for GnuPG
description: |
    Kleopatra is a GUI for GnuPG so it needs a working GnuPG setup.
builddeps  :
    - pkgconfig(libassuan)
    - gpgme-qt-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - kmime-devel
    - libboost-devel
    - libkleo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
