name       : kleopatra
version    : 21.04.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/kleopatra-21.04.0.tar.xz : c03bc7147e35d2994a0a7d323108d6b34e2e2c70768a5481bec3b04da7b6a870
homepage   : https://kde.org/applications/utilities/org.kde.kleopatra
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : Kleopatra is a GUI for GnuPG
description: |
    Kleopatra is a GUI for GnuPG so it needs a working GnuPG setup.
builddeps  :
    - pkgconfig(libassuan)
    - gpgme-qt-devel
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - kmime-devel
    - libboost-devel
    - libkleo-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
